Raise error if zero samples selected for allele frequency calculations
malariagen/malariagen-data-python pull request #52
Opened 2021-06-11 17:19 UTC by cclarkson

resolves #50

2021-06-30 11:30 UTC, alimanfoo requested changes
Thanks @cclarkson, couple of suggestions re using pytest.raises.

2021-06-30 11:30 UTC, alimanfoo commented on tests/test_ag3.py
> +        raise AssertionError("ValueError was not raised")
The conventional way to test whether an exception is raised is to use [pytest.raises](https://docs.pytest.org/en/6.2.x/reference.html#pytest.raises). E.g.:

```suggestion
    with pytest.raises(ValueError):
        _ = ag3.snp_allele_frequencies(
            transcript="AGAP009194-RA",
            cohorts=cohorts,
            site_mask="gamb_colu",
            sample_sets="v3_wild",
            drop_invariant=True,
        )
```

2021-06-30 11:30 UTC, alimanfoo commented on tests/test_ag3.py
> +        raise AssertionError("ValueError was not raised")
```suggestion
    with pytest.raises(ValueError):
        _ = ag3.gene_cnv_frequencies(
            contig=contig, sample_sets="v3_wild", cohorts=cohorts
        )
```

2021-06-30 14:55 UTC, cclarkson commented
Hi @alimanfoo, thanks for the tip. It all looks fine now but the CI fails on linting

 `reserveCache failed: Cache already exists. Scope: refs/pull/52/merge, Key: pre-commit-2-b0a5bffca046e57a4e8ba1313dc5edea302ab8f7dec6bc921412e0d9d194afe5-e285e84222aebc3800ce85f702f96338a0368d68628bdac142f3d04523858c45, Version: 28cdb9f5496f334116f23e86f0063f5d3a9348c2e22425a33171e071aadada7e`

I've had a google but I'm none-the-wiser any ideas?

2021-07-05 09:49 UTC, alimanfoo approved these changes
Thanks Chris!

2021-07-05 11:03 UTC, merged